HLP_LANG=ru
HLP_DOMAIN_MD = mview.ru.md mcedit6.ru.md mcdiff6.ru.md

include ../hlp-lang-include.am

mview.ru.md: $(top_srcdir)/doc/man/ru/mview.md
	cat $(top_srcdir)/doc/man/ru/mview.md > $@

mcedit6.ru.md: $(top_srcdir)/doc/man/ru/mcedit6.md
	cat $(top_srcdir)/doc/man/ru/mcedit6.md > $@

mcdiff6.ru.md: $(top_srcdir)/doc/man/ru/mcdiff6.md
	cat $(top_srcdir)/doc/man/ru/mcdiff6.md > $@
