HLP_LANG=it
HLP_DOMAIN_MD = mview.it.md mcedit6.it.md mcdiff6.it.md

include ../hlp-lang-include.am

mview.it.md: $(top_srcdir)/doc/man/it/mview.md
	cat $(top_srcdir)/doc/man/it/mview.md > $@

mcedit6.it.md: $(top_srcdir)/doc/man/it/mcedit6.md
	cat $(top_srcdir)/doc/man/it/mcedit6.md > $@

mcdiff6.it.md: $(top_srcdir)/doc/man/it/mcdiff6.md
	cat $(top_srcdir)/doc/man/it/mcdiff6.md > $@
