HLP_LANG=es
HLP_DOMAIN_MD = mview.es.md mcedit6.es.md mcdiff6.es.md

include ../hlp-lang-include.am

mview.es.md: $(top_srcdir)/doc/man/es/mview.md
	cat $(top_srcdir)/doc/man/es/mview.md > $@

mcedit6.es.md: $(top_srcdir)/doc/man/es/mcedit6.md
	cat $(top_srcdir)/doc/man/es/mcedit6.md > $@

mcdiff6.es.md: $(top_srcdir)/doc/man/es/mcdiff6.md
	cat $(top_srcdir)/doc/man/es/mcdiff6.md > $@
