HLP_LANG=sr
HLP_DOMAIN_MD = mview.sr.md mcedit6.sr.md mcdiff6.sr.md

include ../hlp-lang-include.am

mview.sr.md: $(top_srcdir)/doc/man/sr/mview.md
	cat $(top_srcdir)/doc/man/sr/mview.md > $@

mcedit6.sr.md: $(top_srcdir)/doc/man/sr/mcedit6.md
	cat $(top_srcdir)/doc/man/sr/mcedit6.md > $@

mcdiff6.sr.md: $(top_srcdir)/doc/man/sr/mcdiff6.md
	cat $(top_srcdir)/doc/man/sr/mcdiff6.md > $@
