HLP_LANG=hu
HLP_DOMAIN_MD = mview.hu.md mcedit6.hu.md mcdiff6.hu.md

include ../hlp-lang-include.am

mview.hu.md: $(top_srcdir)/doc/man/hu/mview.md
	cat $(top_srcdir)/doc/man/hu/mview.md > $@

mcedit6.hu.md: $(top_srcdir)/doc/man/hu/mcedit6.md
	cat $(top_srcdir)/doc/man/hu/mcedit6.md > $@

mcdiff6.hu.md: $(top_srcdir)/doc/man/hu/mcdiff6.md
	cat $(top_srcdir)/doc/man/hu/mcdiff6.md > $@
