HLP_LANG=pl
HLP_DOMAIN_MD = mview.pl.md mcedit6.pl.md mcdiff6.pl.md

include ../hlp-lang-include.am

mview.pl.md: $(top_srcdir)/doc/man/pl/mview.md
	cat $(top_srcdir)/doc/man/pl/mview.md > $@

mcedit6.pl.md: $(top_srcdir)/doc/man/pl/mcedit6.md
	cat $(top_srcdir)/doc/man/pl/mcedit6.md > $@

mcdiff6.pl.md: $(top_srcdir)/doc/man/pl/mcdiff6.md
	cat $(top_srcdir)/doc/man/pl/mcdiff6.md > $@
