name: ci-fedora

on:
  workflow_call:

env:
  CLANG_FORMAT_VERSION: 20.1.3

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: fedora:latest

    permissions:
      contents: read

    steps:
      - name: Install dependencies
        run: |
          dnf install -y \
            git `# Install git inside container` \
            \
            autoconf automake clang-tools-extra gcc gettext-devel groff libtool make pkgconfig \
            check-devel gpm-devel libX11-devel "pkgconfig(ext2fs)" "pkgconfig(glib-2.0)" "pkgconfig(gmodule-2.0)" "pkgconfig(libssh2)" "pkgconfig(slang)" \
            \
            glibc-gconv-extra util-linux `# For tests` \
            python3-pip \
            mandoc `# To render manual pages` \

            pip install clang-format==${{ env.CLANG_FORMAT_VERSION }}

      - uses: actions/checkout@v7


      - name: Lint documentation
        working-directory: maint
        run: ./doctest.py

      - name: Lint sources
        working-directory: maint
        run: ./asciitest.py

      - name: Bootstrap build system
        run: ./autogen.sh

      - name: Build default configuration
        run: |
          useradd --home "$(pwd)" test
          chown -R test "$(pwd)"

          su - test -c ' \
            ./configure \
              --prefix="$(pwd)/install-prefix" \
              --enable-option-checking=fatal \
              --enable-mclib \
              --enable-werror \
              && \
            \
            echo "Checking formatting..." && \
            clang-format --version && \
            make indent && \
            echo "Changed files after formatting:" && \
            git diff --name-only -- '*.c' '*.h' && \
            git diff --exit-code -- '*.c' '*.h' && \
            \
            make -j$(nproc) && \
            make check && \
            make install \
          '

      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: test-suite-logs-fedora
          path: ./**/test-suite.log
